import { Card, CardContent, Paper, Theme, Typography } from '@mui/material';
import { Box, styled, useTheme } from '@mui/system';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React, { FC } from 'react';

const GutterContainer: FC = ({ children }) => (
  <Box
    sx={{
      paddingLeft: '2rem',
      paddingRight: '2rem',
    }}
  >
    <Box
      sx={{
        maxWidth: '75rem',
        margin: 'auto',
      }}
    >
      {children}
    </Box>
  </Box>
);

const Home: NextPage = () => {
  const theme = useTheme<Required<Theme>>();
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        component='header'
        sx={{
          color: theme.palette.text.secondary,
          bgcolor: theme.palette.grey[900],
        }}
      >
        <GutterContainer>
          <Typography variant='h1' component='h1'>
            BurnerAPI
          </Typography>
          <Typography variant='h3' component='p'>
            Instanly turn a JSON string into a REST endpoint
          </Typography>
        </GutterContainer>
      </Box>

      <Box
        component='main'
        sx={{
          position: 'relative',
          minHeight: '5rem',
          '&:before': {
            content: '" "',
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: '5rem',
            backgroundColor: theme.palette.grey[900],
            zIndex: -1,
          },
        }}
      >
        <GutterContainer>
          <Card>
            <CardContent>
              <Typography variant='h3' component='h2'>
                Data
              </Typography>
              <Typography variant='body1' color={theme.palette.text.disabled}>
                Paste JSON into here
              </Typography>
            </CardContent>
          </Card>
        </GutterContainer>
      </Box>
      <GutterContainer>
        <Box component='footer'>Footer</Box>
      </GutterContainer>
    </Box>
  );
};

export default Home;
