import {
  Button,
  Card,
  CardContent,
  Color,
  PaletteColor,
  Theme,
  Typography,
} from '@mui/material';
import { Box, useTheme } from '@mui/system';
import GenerateSchema from 'generate-schema';
import json5 from 'json5';
import compare from 'just-compare';
import type { NextPage } from 'next';
import dynamic from 'next/dynamic';
import Head from 'next/head';
import React, { FC, useState } from 'react';
import Code from '../Code';
import ParamsTable from './ParamsTable';
const JSONEditor = dynamic(() => import('../json-editor'), {
  loading: () => <>...</>,
  ssr: false,
});

const Spacer: FC<{ size?: string }> = ({ size = '1rem' }) => (
  <Box sx={{ height: size, width: size }} />
);

const GutterContainer: FC = ({ children }) => (
  <Box
    sx={{
      paddingLeft: '2rem',
      paddingRight: '2rem',
    }}
  >
    <Box
      sx={{
        maxWidth: '75rem',
        margin: 'auto',
      }}
    >
      {children}
    </Box>
  </Box>
);

const Criterion: FC<{ success: boolean }> = (props) => {
  const theme = useTheme<Required<Theme>>();

  const palette: Partial<Color> & PaletteColor = props.success
    ? theme.palette.success
    : theme.palette.error;
  return (
    <Box sx={{ display: 'flex', marginTop: '1rem' }}>
      <Box
        sx={{
          background: palette[50],
          padding: '.5rem',
          borderRadius: '2rem',
        }}
      >
        <Box
          sx={{
            background: palette.light,
            padding: '.5rem',
            borderRadius: '1rem',
          }}
        ></Box>
      </Box>
      <Box sx={{ flex: 1, alignSelf: 'center', paddingLeft: '0.5rem' }}>
        <Typography variant='body1'>{props.children}</Typography>
      </Box>
    </Box>
  );
};

const Home: NextPage = () => {
  const theme = useTheme<Required<Theme>>();
  const [data, setData] = useState<string>(`[

]`);

  const prettify = (s: string) => {
    const asJson = json5.parse(s);
    const asString = json5.stringify(asJson, null, 4);
    return asString;
  };

  const analyseJSONString = (s: string) => {
    const response = {
      isValidJSON5: false,
      isArray: false,
      isntEmpty: false,
      isArrayOfObjects: false,
      isArrayOfSameType: false,
    };

    let json: any;
    try {
      json = json5.parse(s);
      response.isValidJSON5 = true;
    } catch {
      return response;
    }

    if (Array.isArray(json)) {
      response.isArray = true;
    } else {
      return response;
    }

    if (json.length >= 1) {
      response.isntEmpty = true;
    } else {
      return response;
    }

    const schema = GenerateSchema.json('data', json);
    console.log(schema.items);
    if (schema.items.type === 'object') {
      response.isArrayOfObjects = true;
    } else {
      return response;
    }

    const keys = Object.keys(schema.items.properties);
    const requiredKeys = schema.items.required;
    const eachPropHasSingleType = (
      Object.values(schema.items.properties) as { type: any }[]
    ).every((o) => typeof o.type === 'string');
    if (
      (!requiredKeys || compare(keys, requiredKeys)) &&
      eachPropHasSingleType
    ) {
      response.isArrayOfSameType = true;
    } else {
      return response;
    }

    return response;
  };

  const analysedData = analyseJSONString(data);

  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box
        component='header'
        sx={{
          color: theme.palette.text.secondary,
          bgcolor: theme.palette.grey[900],
        }}
      >
        <GutterContainer>
          <Typography variant='h1' component='h1'>
            BurnerAPI
          </Typography>
          <Typography variant='h3' component='p'>
            Instanly turn a JSON string into a REST endpoint
          </Typography>
        </GutterContainer>
      </Box>

      <Box
        component='main'
        sx={{
          position: 'relative',
          minHeight: '5rem',
          '&:before': {
            content: '" "',
            position: 'absolute',
            top: 0,
            left: 0,
            right: 0,
            height: '5rem',
            backgroundColor: theme.palette.grey[900],
            zIndex: -1,
          },
        }}
      >
        <GutterContainer>
          <Card elevation={2}>
            <CardContent>
              <Typography variant='h3' component='h2'>
                Data
              </Typography>
              <Typography variant='body1' color={theme.palette.text.disabled}>
                Paste JSON into here
              </Typography>
              <Box
                sx={{
                  position: 'relative',
                }}
              >
                <JSONEditor
                  style={{
                    width: '100%',
                    borderRadius: '.5rem',
                    paddingTop: '0.5rem',
                  }}
                  value={data}
                  onChange={(newData) => setData(newData)}
                />

                <Button
                  variant='contained'
                  color='secondary'
                  size='small'
                  disabled={!analysedData.isValidJSON5}
                  onClick={() => setData(prettify(data))}
                  style={{
                    position: 'absolute',
                    bottom: '0.5rem',
                    right: '0.5rem',
                    zIndex: 1,
                    borderRadius: '100rem',
                  }}
                >
                  Prettify
                </Button>
              </Box>

              <Criterion success={analysedData.isValidJSON5}>
                Valid JSON
              </Criterion>
              <Criterion success={analysedData.isArray}>
                Valid JSON array
              </Criterion>
              <Criterion success={analysedData.isntEmpty}>
                Array is not emptys
              </Criterion>
              <Criterion success={analysedData.isArrayOfObjects}>
                All items are objects
              </Criterion>
              <Criterion success={analysedData.isArrayOfSameType}>
                All items have the same type
              </Criterion>
              <Button
                variant='contained'
                disabled={!analysedData.isArrayOfSameType}
                onClick={() => {}}
                style={{ width: '100%', marginTop: '1rem' }}
              >
                Create API
              </Button>
            </CardContent>
          </Card>
        </GutterContainer>
      </Box>
      <GutterContainer>
        <Spacer size='1rem' />

        <Typography variant='h3' component='h2'>
          Endpoints
        </Typography>

        <Typography variant='h4' component='p'>
          OData
        </Typography>
        <Spacer size='.5rem' />

        <Card elevation={2}>
          <CardContent>
            <Typography variant='h3' component='h2'>
              Get all
            </Typography>
            <Spacer size='.5rem' />
            <Typography variant='body1' color={theme.palette.text.disabled}>
              cURL
            </Typography>
            <Box
              sx={{
                borderRadius: '.5rem',
                backgroundColor: theme.palette.grey['900'],
                color: 'white',
                padding: '.5rem 1rem',
              }}
            >
              <Code language='bash'>{`curl "https://api.tomhowland.com/odata/rec1748295?skip=0"`}</Code>
            </Box>
            <Spacer size='.5rem' />
            <Typography variant='body1' color={theme.palette.text.disabled}>
              Response
            </Typography>
            <Box
              sx={{
                borderRadius: '.5rem',
                backgroundColor: theme.palette.grey['900'],
                color: 'white',
                padding: '.5rem 1rem',
              }}
            >
              <Code language='json5'>{`{
    yello: 12, // ruh ruh 
    "crumbly": 'ddddd',
    randy: {
      ishe: false
    }
}`}</Code>
            </Box>
            <Spacer size='.5rem' />
            <Typography variant='body1' color={theme.palette.text.disabled}>
              Parameters
            </Typography>
            <ParamsTable />
          </CardContent>
        </Card>
      </GutterContainer>
      <GutterContainer>
        <Box component='footer'>Footer</Box>
      </GutterContainer>
    </Box>
  );
};

export default Home;

// PreWork is diff from oroject
// they want me to mark,
// callum can help
// they expect me to do it
//
